### ISSUE TITLE
WHAT IS `EKSClusterCertificateName ` ?

### ISSUE THREAD

**Issue by saikatharryc** [y13i/aws-eks-example#1]
Hi, i have deployed `cfn.yml` through the aws cloudformation dashboard.
in there in output section i can see all the variables needed. only i cant see anything named `EKSClusterCertificateName`.
anyhelp with this?

**Comment by y13i** [comment]
Hello @saikatharryc 
I believe it is a typo for `EKSClusterName`.

**Comment by saikatharryc** [comment]
thanks for letting know!
